"""Derive inspectable tables from closed evidence; no models or new hands."""
import argparse
from collections import defaultdict
import csv
import gzip
import json
from pathlib import Path


def write_csv(path, rows):
    fields=list(dict.fromkeys(k for row in rows for k in row))
    with path.open('w',newline='') as f:
        writer=csv.DictWriter(f,fields,lineterminator='\n');writer.writeheader();writer.writerows(rows)


def interval(result):
    return f"{result['bb_per_100']:+.2f} [{result['ci95'][0]:+.2f}, {result['ci95'][1]:+.2f}]"


def generate(root,out):
    out.mkdir(parents=True,exist_ok=False)
    summary=json.loads((root/'comparison/summary.json').read_text())
    calibration=json.loads((root/'calibration-confirmation/summary.json').read_text())
    specs={s['name']:s for s in summary['plan']['models']}
    panel_rows=[]
    for source,panels in (('calibration',calibration['panels']),('model',summary['panels'])):
        for p in panels:
            for position,result in [('overall',p['overall']),*p['positions'].items()]:
                panel_rows.append({'source':source,'policy':p['policy'],'mode':p['mode'],'control':p['panel'],
                    'position':position,'bb_per_100':result['bb_per_100'],'ci95_low':result['ci95'][0],
                    'ci95_high':result['ci95'][1],'paired_blocks':result['blocks'],
                    **({f'all_positions_{k}':v for k,v in p['counts'].items()} if position=='overall' else {})})
    write_csv(out/'panels.csv',panel_rows)
    decisions=[];representatives={};partitions=defaultdict(lambda:[0,0,0,0])
    for spec in summary['plan']['models']:
        case_rows=[c for c in summary['decision_diagnostics'] if c['model']==spec['name']]
        by_hand=defaultdict(list)
        for c in case_rows:by_hand[c['mode'],c['block'],c['rotation']].append(c)
        with gzip.open(root/'comparison'/(spec['name']+'.hands.jsonl.gz'),'rt') as f:
            for line in f:
                row=json.loads(line);counts=row['tails']['counts']
                key=spec['name'],row['mode'],row['tails']['first_large_raise_response']
                totals=partitions[key];totals[0]+=1;totals[1]+=row['target_chips']
                totals[2]+=counts['full_stack_wins'];totals[3]+=counts['full_stack_losses']
                for c in by_hand[row['mode'],row['block'],row['rotation']]:
                    observed=row['actions'][c['index']]['observation'];chosen=c['legal_alternatives'][c['selected_index']]
                    item={'model':c['model'],'mode':c['mode'],'block':c['block'],'rotation':c['rotation'],
                        'action_index':c['index'],'street':c['street'],'position':c['position'],'priority':c['priority'],
                        'own_cards':' '.join(observed['hole_cards']),'board':' '.join(observed['board']),
                        'pot_chips':observed['pot'],'call_chips':observed['call_amount'],'root_trained':c['root_trained'],
                        'selected_alternative':chosen['name'],'selected_raise_to':chosen['raise_to'],
                        'gap_bb':c['gap_bb'],'ci95_low_bb':c['gap_ci95_bb'][0],'ci95_high_bb':c['gap_ci95_bb'][1],
                        'range_ess':c['range']['effective_sample_size'],'range_particles':c['range']['particles'],
                        'range_resets':c['range']['resets'],'selection_worlds':c['selection_worlds'],
                        'evaluation_worlds':c['evaluation_worlds'],'root_alternatives_json':json.dumps(c['legal_alternatives'],sort_keys=True),
                        'selection_means_json':json.dumps(c['selection_action_mean_bb']),
                        'evaluation_means_json':json.dumps(c['evaluation_action_mean_bb']),
                        'evaluation_mixture_bb':c['evaluation_policy_mean_bb'],
                        'continuation_trained':c['continuation_lookups']['trained'],'continuation_fallback':c['continuation_lookups']['fallback']}
                    decisions.append(item)
                    # Choose representatives by the same frozen coordinate priority,
                    # within the first lineage/B100M; never by loss or estimated gap.
                    if spec['seed']==2026093001 and spec['milestone']==100000000:
                        key=c['mode'],c['street']
                        if key not in representatives or c['priority']<representatives[key]['priority']:representatives[key]=item
    write_csv(out/'decisions.csv',sorted(decisions,key=lambda r:(r['model'],r['mode'],r['street'],r['position'],r['priority'])))
    write_csv(out/'whole-hand-partitions.csv',[{'model':model,'mode':mode,'first_large_response':response,
        'hands':n,'sum_whole_hand_chips':chips,'whole_hand_bb_per_100':chips/n,
        'full_stack_wins':wins,'full_stack_losses':losses}
        for (model,mode,response),(n,chips,wins,losses) in sorted(partitions.items())])
    lines=['# Derived tables','', 'Generated by `scripts/report_strong_hu20.py`. Intervals are exploratory paired 95%; modes stay separate.',
           'Counts are actions/opportunities or completed hands as labelled. Whole-hand partitions are not individual-bet EV.','',
           '## Calibration confirmation','', '| Mode | Control | Heuristic BB/100 [95%] | BB / button point | Stack wins / losses (128 hands) |',
           '| --- | --- | --- | --- | --- |']
    for p in calibration['panels']:
        lines.append(f"| {p['mode']} | {p['panel']} | {interval(p['overall'])} | {p['positions']['big_blind']['bb_per_100']:+.2f} / {p['positions']['button']['bb_per_100']:+.2f} | {p['counts']['full_stack_wins']} / {p['counts']['full_stack_losses']} |")
    lines+=['','## Saved checkpoint panels','', '| Mode | Seed | Nodes | Target BB/100 [95%] | BB / button point | Large actions / opportunities | Rival folds / continues | Stack wins / losses (1,024 hands) | Fallback / decisions |',
            '| --- | --- | --- | --- | --- | --- | --- | --- | --- |']
    for p in summary['panels']:
        s=specs[p['policy']];c=p['counts']
        lines.append(f"| {p['mode']} | {s['seed']} | {s['milestone']//1000000}M | {interval(p['overall'])} | {p['positions']['big_blind']['bb_per_100']:+.2f} / {p['positions']['button']['bb_per_100']:+.2f} | {c['large_actions']} / {c['large_opportunities']} | {c['rival_folds']} / {c['rival_continuations']} | {c['full_stack_wins']} / {c['full_stack_losses']} | {c.get('fallback',0)} / {c['target_decisions']} |")
    lines+=['','## Paired changes','', '| Mode | Seed | B500M minus B100M BB/100 [95%] |','| --- | --- | --- |']
    for c in summary['seed_changes']:lines.append(f"| {c['mode']} | {c['seed']} | {interval(c['500m_minus_100m'])} |")
    lines+=['','## Representative decisions','', 'Lowest frozen coordinate priority per mode/street in first-lineage B100M; no payoff-based selection.',
            'Exact root mixtures, independent-half means and all 192 cases are in `decisions.csv`; fresh-world continuation traces are in the original compressed files.',
            'Conditional gaps are BB per decision, not BB/100 or proven errors. Intervals omit range/continuation bias and multiple-case adjustment.','',
            '| Mode / street | Block / seat / index / position | Own cards; board | Selected alternative | Held-out gap [95%] BB | Range ESS |',
            '| --- | --- | --- | --- | --- | --- |']
    for key in sorted(representatives):
        c=representatives[key];action=c['selected_alternative']+(f" to {c['selected_raise_to']}" if c['selected_raise_to'] is not None else '')
        lines.append(f"| {c['mode']} / {c['street']} | {c['block']} / {c['rotation']} / {c['action_index']} / {c['position']} | {c['own_cards']}; {c['board'] or '—'} | {action} | {c['gap_bb']:+.3f} [{c['ci95_low_bb']:+.3f}, {c['ci95_high_bb']:+.3f}] | {c['range_ess']:.2f} |")
    (out/'tables.md').write_text('\n'.join(lines)+'\n')


def main():
    p=argparse.ArgumentParser(description=__doc__);p.add_argument('--evidence',type=Path,required=True);p.add_argument('--out',type=Path,required=True)
    a=p.parse_args();generate(a.evidence,a.out)


if __name__=='__main__':main()
